habilities:
  en: Habilities
  fr: Compétences
jobs:
  en: Jobs
  fr: Expériences professionnelles
home:
  en: Home
  fr: Accueil
articles:
  en: Articles
  fr: Articles
projects:
  en: Projects
  fr: Projets
about:
  en: About
  fr: A propos
language:
  fr: Langue
  en: Language
en:
  fr: Anglais
  en: English
fr:
  fr: Français
  en: French
