name: deploy-ghpages

on:
  push:
    branches:
      - main
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - id: Build-Vue
        uses: ashkantaravati/NuxtToGithubPages@v1.0
        with:
          username: 'svandecappelle'
          reponame: 'svandecappelle.github.io'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
