name: deploy-ghpages

on:
  push:
    branches:
      - main
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v3
      - id: Build-Vue
        uses: ashkantaravati/NuxtToGithubPages@v1.0
        with:
          username: 'svandecappelle'
          reponame: 'svandecappelle.github.io'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
